### ISSUE TITLE
run.sh shortcut in kodi

### ISSUE THREAD

**Issue by WilliamStam** [HazCod/LimeRPi2-kodi#2]
"You can even create a link in Kodi to make it as seamless as possible. "

im using aeon nox. i added a system.exec(/storage/moonlight/run.sh) shortcut but it doesnt work so nicely. 

playing around with the shortcut opening a python script which then executes the run.sh instead. running run.sh closes kodi and then starts it again without the moonlight stuff running. 

will post when i get it right

**Comment by hazcod** [comment]
Hmm, and it runs successfuly from SSH?

**Comment by WilliamStam** [comment]
yips. lastnight while trying to get it to work again (since the limlight to moonlight change over) i read somewhere that when kodi closes it closes its session or something. so in effect it stops the script. (i always thought it was a permission problem somehting like kodi not running it as root etc)

the logs didnt give any clues previously. was just kodi shutting down kodi starting type stuff. 

it was late.. i opened a million web pages.. now for the life of me i cant find the relevant page. they said somehting bout calling a python script that had somehting bout screen etc.

**Comment by hazcod** [comment]
@WilliamStam , you have to prepend it with systemd-run.
So e.g.;  `system.exec(systemd-run /storage/moonlight/run.sh)`

68828da68ffc8276fedfad9c8703106b21d4ef3b
