### ISSUE TITLE
Starting the run.sh script from within Kodi

### ISSUE THREAD

**Issue by Serg86** [HazCod/LimeRPi2-kodi#3]
The line "system.exec("systemd-run /storage/moonlight/run.sh")" does not work for me. It spawns a new Kodi process every time I try to run it and never even gets to the script. It does this every time it doesn't know what it is supposed to do. Removing the systemd-run command and only leaving the path to the script runs the script successfully. Once I remade the run.sh and forgot to chmod it, again it crashed and spawned a second process.

However, there is a new problem, I can't start moonlight, output says X Server is probably running even though Kodi has been killed.
Full output:

```
X server is propably running
Please exit the X server for a lower latency
Fix problems or start application with parameter -notest
```

With the -notest parameter:

```
Jun 10, 2015 4:00:19 PM com.limelight.LimeLog severe
SEVERE: uniqueid.dat (Read-only file system)
Starting Steam
java.io.FileNotFoundException: client.crt (Read-only file system)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at com.limelight.binding.crypto.PcCryptoProvider.saveCertKeyPair(Unknown Source)
        at com.limelight.binding.crypto.PcCryptoProvider.generateCertKeyPair(Unknown Source)
        at com.limelight.binding.crypto.PcCryptoProvider.getClientCertificate(Unknown Source)
        at com.limelight.nvstream.http.PairingManager.<init>(Unknown Source)
        at com.limelight.nvstream.http.NvHTTP.<init>(Unknown Source)
        at com.limelight.nvstream.NvConnection.startApp(Unknown Source)
        at com.limelight.nvstream.NvConnection.establishConnection(Unknown Source)
        at com.limelight.nvstream.NvConnection.access$200(Unknown Source)
        at com.limelight.nvstream.NvConnection$1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
Device not paired with computer
Connection Error Starting Steam failed
```

However I fixed this by including "cd /storage/moonlight/" above the java -jar ... command in the script.
Steam starts up now, but still I would like to solve the X Server issue.

Raspberry Pi 2, OpenELEC 5.08, Moonlight (Limelight) 1.2.2.

PS: When changing the library path in run.sh, it checks for "/storage/limeligt".

**Comment by hazcod** [comment]
Thank you, modified the typo in fc2fd05f5ac446ca0e2aa584d636e62001fcbdd0.

About the systemd-run, this was told to me by a OE developer. Could you try a reboot and running it without the systemd-run ?

**Comment by Serg86** [comment]
You mean with just the script path?
**[*]** _Removing the systemd-run command and only leaving the path to the script runs the script successfully._**[*]**

That's what I am doing and it is working. I am actually at a loss about stopping Kodi correctly.

I stumbled upon the code in moonlight that produces the X Server error message via google. My novice level programming skills tell me that, apparently, all it does is check the global $DISPLAY variable. If it's empty, it proceeds, if not it spits out this error message.

Running the same script from a console via SSH shuts down Kodi entirely, including clearing the $DISPLAY variable. But that is actually not the main reason I need to do this. I managed to manually scramble together all the dependencies for xboxdrv to make it run in OpenELEC. My DualShock 3 is working perfectly, even with Bluetooth. However if I connect it while Kodi is still running, it will not release it. Unless the script was run via SSH.

I've tried "sleep 30" after "systemctl stop kodi", didn't work. Neither did moving the run.sh script to startup.sh, and all run.sh does is run "/storage/moonlight/startup.sh &", to make run.sh close it's process, cutting all ties to Kodi. While that was happening, I checked the processes via SSH and Kodi wasn't running.

Nothing seems to work.

**EDIT :**

Ok I finally got it. run.sh now starts the startup.sh script using: "systemd-run /storage/moonlight/startup.sh" and it works.

**Comment by hazcod** [comment]
Could you share your current startup.sh or do a pull request?

**Comment by Serg86** [comment]
The startup.sh that I use is actually bigger than that, I've removed the stuff that is specific to my setup and changed some values to generic/default ones. In addition to the code below, I start xboxdrv with my configuration and check to see if the controller is connected or not before proceeding, because xboxdrv needs the specific input device at launch for bluetooth, otherwise it will not work until I restart it. I also added the comments. Feel free to make any changes you wish to it.

```
#!/bin/sh

##############################
#    ADJUSTABLE SETTINGS     #
##############################

# IP address of host PC

IP='192.168.0.0'

# The path where limelight.jar is located
# Default "/storage/moonlight"

MAINPATH="/storage/moonlight"

# Path to the Java executable
# Default "/storage/java/bin"

JAVAPATH="/storage/java/bin"

# Change according to your preferences

STREAMSETTINGS="-720 -60fps -mapping $MAINPATH/controller.map"

##############################
# DO NOT EDIT ANYTHING BELOW #
##############################

# Check if the host PC is online, if not, send a notification to Kodi
if [ ! ping -W 1 -c 1 $IP > /dev/null 2>&1 && echo 'Online' ]; then
    echo 'PC Offline, turn on host PC and retry.'
    kodi-send --action=notification"(PC Offline, Turn on the host PC and retry.)"
else
    # Changing working directory to the specified MAINPATH
    cd $MAINPATH

    # Checking if the 'global library path variable' contains the main path
    if [[ ! $LD_LIBRARY_PATH == *"$MAINPATH"* ]]; then
        export LD_LIBRARY_PATH=$MAINPATH:$LD_LIBRARY_PATH
    fi

    # Load sound module if it is not loaded.
    if ! lsmod | grep "snd_bcm2835" &> /dev/null ; then
        modprobe snd_bcm2835
    fi

    # Stop Kodi
    systemctl stop kodi

    # Start limelight
    $JAVAPATH/java -jar $MAINPATH/limelight.jar stream $IP $STREAMSETTINGS

    # Restart Kodi
    systemctl start kodi
fi
```

This is my run.sh for completeness:

```
#!/bin/sh

systemd-run /storage/moonlight/startup.sh
```

Slightly unrelated, but do you have an updated update.sh for me to try from the other issue? I would've fixed it myself but I sort of google my way through shell scripting and can't find anything other than bash specific code examples.

**Comment by hazcod** [comment]
Thanks! And sure, this is what I have right now:
(Still stuck on `local i ver1=($1) ver2=($2)` as I only know the bash syntax..)

```
#!/bin/sh

vercomp () {
    if test "$1" = "$2"
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    local ver2_m1=$((${#ver2[@]}-1))
    for i in {${#ver1[@]}..${ver2_m1}}
    do
        ver1[i]=0
    done
    local ver1_m1=$((${#ver1[@]}-1))
    for i in {0..${ver1_m1}}
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

downloadFile() {
    # $1 : first argument must be version
    # $2 : second argument must be file to download
    curl -L -O -s "https://github.com/irtimmer/moonlight-embedded/releases/download/v$1/$2"
}

updateMoonlight() {
    FILE=version
    releases=$(curl --silent -L https://github.com/irtimmer/moonlight-embedded/releases/latest)
    current_version=$(if [ -f "$FILE" ]; then cat $FILE; fi)
    latest_version=$(echo "$releases" | egrep -o "/releases/download/v([0-9]\.*)+/" | egrep -o "v([0-9]\.*)+" | cut -c 2- | head -n 1)

    v_cmp=$(vercomp "$latest_version" "$current_version")

    if [ ! -f "$FILE" ] || test "$v_cmp" = "1"; then
        echo "Updating moonlight to $latest_version"
        downloadFile "$latest_version" libopus.so
        downloadFile "$latest_version" limelight.jar
        echo "$latest_version" > "$FILE"
        return 0
    else
        echo "No update necessary, at latest version. ($latest_version)"
        return 1
    fi
}

updateMoonlight
```

**Comment by hazcod** [comment]
Discussion about the other bug can be done in the respective bug thread.
I changed some things based on your findings in 2942dffb6796bd1fcde7e6a037ff571fd1e60182.
Thank you!
