### ISSUE TITLE
Launcher not working

### ISSUE THREAD

**Issue by alejostenuki** [HazCod/LimeRPi2-kodi#4]
The run.sh file points to startup.sh, which hasn't been defined.

If I point it to moonlight.sh, I'll get a "Running as unit run-1952.service". however, nothing will start on rpi, I'm currently through ssh.

If I try to create a launcher with advanced launcher it asks for a few options which I don't know. Mainly, it asks for platform... without any rpi option available...

By the way, if I launch through ssh"  /storage/java/bin/java -jar /storage/moonlight/limelight.jar stream "$IP"" Steam is launched and everything is fine but the image: it's transparent. I'm seeing the kodi background + steam streaming

**Comment by hazcod** [comment]
Thanks, I fixed the typos in cfde98df1534a3b8f2915f3ac4361a04abbfe4bc.

Advanced launcher will ask for a bunch of options, can't remember what I picked, best to ask them.

~~What do you mean it's transparent?~~ You need to shut down kodi before running it. systemctl stop kodi

**Comment by alejostenuki** [comment]
I suggested some modifications to the readme file.

I've tried reinstalling everything. I'm stuck at the same point: creating the advanced installer shortcut. However, last time I could stream it through ssh, now I can't. 

Ah, I didn't shut down kodi. That should be part of the script ;)

**Comment by hazcod** [comment]
systemctl stop kodi is part of the script btw
